import type { ScopeFeedbackTag } from './scope';
import type { TranslationFeedbackTag } from './translation';
import type { ProofFeedbackTag } from './proof';
export type FeedbackTag = ScopeFeedbackTag | TranslationFeedbackTag | ProofFeedbackTag;
export type FeedbackTemplate = Partial<Record<FeedbackTag, string>>;
export type FeedbackResult = { correct: boolean; tag: FeedbackTag; message: string };
export { resolveFeedback, checkMainConnectiveSelection, expectedMainConnectiveNodeId } from './scope';
export type { TranslationFeedbackTag, TranslationFeedbackTemplate, TranslationFeedbackResult } from './translation';
export { classifyTranslation, resolveTranslationFeedback } from './translation';
export type { ProofFeedbackTag } from './proof';
export { resolveProofFeedback } from './proof';
