import type { ConnectiveKind, Formula, Term } from '../ast/types';
import { pred, not, and, or, imp, iff, forall, exists, termFromName } from '../ast/types';
export class ParseError extends Error { constructor(message: string) { super(message); this.name = 'ParseError'; } }
type Token = | { type: 'ident'; value: string } | { type: 'quant'; value: 'forall' | 'exists' } | { type: 'op'; value: string } | { type: 'lparen' } | { type: 'rparen' } | { type: 'comma' } | { type: 'eof' };
const OPERATORS = new Set(['¬', '!', '∧', '&', '∨', '|', '→', '->', '↔', '<->']);
function tokenize(input: string): Token[] { const tokens: Token[] = []; let i = 0; while (i < input.length) { const ch = input[i]; if (/\s/.test(ch)) { i += 1; continue; } if (ch === '(') { tokens.push({ type: 'lparen' }); i += 1; continue; } if (ch === ')') { tokens.push({ type: 'rparen' }); i += 1; continue; } if (ch === ',') { tokens.push({ type: 'comma' }); i += 1; continue; } if (ch === '∀') { tokens.push({ type: 'quant', value: 'forall' }); i += 1; continue; } if (ch === '∃') { tokens.push({ type: 'quant', value: 'exists' }); i += 1; continue; } if (input.startsWith('->', i) || input.startsWith('<->', i)) { tokens.push({ type: 'op', value: input.startsWith('<->', i) ? '<->' : '->' }); i += input.startsWith('<->', i) ? 3 : 2; continue; } if (OPERATORS.has(ch)) { tokens.push({ type: 'op', value: ch }); i += 1; continue; } if (/[A-Za-z]/.test(ch)) { let name = ch; i += 1; while (i < input.length && /[A-Za-z0-9_]/.test(input[i])) { name += input[i]; i += 1; } tokens.push({ type: 'ident', value: name }); continue; } throw new ParseError(`Unexpected character '${ch}' at position ${i}`); } tokens.push({ type: 'eof' }); return tokens; }
class Parser { private index = 0; constructor(private readonly tokens: Token[]) {} parse(): Formula { const formula = this.parseIff(); this.expect('eof'); return formula; } private parseIff(): Formula { let left = this.parseImp(); while (this.matchOp('↔', '<->')) left = iff(left, this.parseImp()); return left; } private parseImp(): Formula { let left = this.parseOr(); while (this.matchOp('→', '->')) left = imp(left, this.parseOr()); return left; } private parseOr(): Formula { let left = this.parseAnd(); while (this.matchOp('∨', '|')) left = or(left, this.parseAnd()); return left; } private parseAnd(): Formula { let left = this.parseNot(); while (this.matchOp('∧', '&')) left = and(left, this.parseNot()); return left; } private parseNot(): Formula { if (this.matchOp('¬', '!')) return not(this.parseNot()); return this.parseQuantifier(); } private parseQuantifier(): Formula { const token = this.peek(); if (token.type === 'quant') { this.index += 1; const boundVar = this.expectIdent('Expected bound variable after quantifier'); const body = this.parseQuantifier(); return token.value === 'forall' ? forall(boundVar, body) : exists(boundVar, body); } return this.parsePrimary(); } private parsePrimary(): Formula { if (this.match('lparen')) { const formula = this.parseIff(); this.expect('rparen'); return formula; } const name = this.expectIdent('Expected formula'); if (this.match('lparen')) { const args = this.parseTermList(); this.expect('rparen'); return pred(name, args); } return pred(name, []); } private parseTermList(): Term[] { if (this.match('rparen')) { this.index -= 1; return []; } const terms = [this.parseTerm()]; while (this.match('comma')) terms.push(this.parseTerm()); return terms; } private parseTerm(): Term { return termFromName(this.expectIdent('Expected term')); } private peek(): Token { return this.tokens[this.index]; } private match(type: Token['type']): boolean { if (this.peek().type === type) { this.index += 1; return true; } return false; } private matchOp(...values: string[]): boolean { const token = this.peek(); if (token.type === 'op' && values.includes(token.value)) { this.index += 1; return true; } return false; } private expect(type: Token['type']): void { if (!this.match(type)) throw new ParseError(`Expected ${type}, got ${this.peek().type}`); } private expectIdent(message: string): string { const token = this.peek(); if (token.type !== 'ident') throw new ParseError(`${message}, got ${token.type}`); this.index += 1; return token.value; } }
export function parse(input: string): Formula { return new Parser(tokenize(input.trim())).parse(); }
export function mainConnective(formula: Formula): ConnectiveKind | 'pred' { return formula.kind; }
