import { format, type RuleId } from '../../../engine';
import { proofUi, ui, type ProofUiCopy } from '../../i18n';
import type { AppState } from '../state';
import { getProofExerciseConfig } from './exercise-config';
function ruleLabel(copy: ProofUiCopy, rule: RuleId): string { if (rule === 'mp') return copy.ruleMp; if (rule === 'and-elim') return copy.ruleAndElim; return rule; }
function justificationLabel(locale: AppState['locale'], line: { hidden: boolean; justification: string | null }): string { const copy = proofUi(locale); if (line.hidden) return copy.missingLine; if (line.justification === 'premise') return copy.premise; if (line.justification === 'mp') return copy.ruleMp; if (line.justification === 'and-elim') return copy.ruleAndElim; return ''; }
export function renderProofExerciseBody(state: AppState): string {
  const config = getProofExerciseConfig(state.exercise.id); if (!config) return ''; const copy = proofUi(state.locale);
  const repairing = state.phase === 'answered' && state.feedback?.correct === false && state.attempt.status !== 'finalized';
  const editable = state.phase === 'ready' || repairing;
  const rows = state.proofLines.map((line) => { const formula = line.hidden && state.phase === 'answered' && state.proofDerivedFormula ? state.proofDerivedFormula : line.formula ? format(line.formula) : '?'; const citeable = !line.hidden && line.lineNumber - 1 < config.hiddenLineIndex && editable; const cited = state.proofCites.includes(line.lineNumber); const citeBtn = citeable ? `<button type="button" class="proof-cite-chip${cited ? ' selected' : ''}" data-action="proof-toggle-cite" data-line="${line.lineNumber}" aria-pressed="${cited}">${line.lineNumber}</button>` : `<span class="proof-line-num">${line.lineNumber}</span>`; return `<li class="proof-line${line.hidden ? ' proof-line-missing' : ''}"><span class="proof-line-head">${citeBtn}<span class="proof-formula">${formula}</span></span><span class="proof-just">${justificationLabel(state.locale, line)}</span></li>`; }).join('');
  const ruleBtns = config.allowedRules.map((rule) => { const selected = state.proofRule === rule; return `<button type="button" class="proof-rule-btn${selected ? ' selected' : ''}" data-action="proof-select-rule" data-rule="${rule}" aria-pressed="${selected}"${editable ? '' : ' disabled'}>${ruleLabel(copy, rule)}</button>`; }).join('');
  return `<section class="proof-panel" aria-label="${copy.panelAria}"><ol class="proof-lines">${rows}</ol><div class="proof-palette"><h2 class="panel-title">${copy.ruleTitle}</h2><div class="proof-rule-row">${ruleBtns}</div><p class="proof-hint">${copy.citeHint}</p></div></section>`;
}
export function renderProofActions(state: AppState, hideContinue = false): string { const copy = ui(state.locale); if (state.attempt.status === 'finalized') return hideContinue ? '' : `<button type="button" class="primary" data-action="next">${copy.continue}</button>`; return `<button type="button" class="primary" data-action="check-proof">${proofUi(state.locale).check}</button>`; }
